AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless service to transform json-to-csv

Resources:
  App:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      ImageUri: "lambda-csv-to-json:latest"
      Architectures:
        - x86_64
      Timeout: 200
      MemorySize: 512
      Environment:
        Variables:
          AWS_DEFAULT_REGION: "us-east-1"
          AWS_REGION: "us-east-1"
          AWS_SECRET_ACCESS_KEY: ""
          AWS_ACCESS_KEY_ID: ""
          BUCKET_NAME: ""
          CSV_FILE_NAME: ""
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: arn:aws:sns:us-east-1:123456789012:my_topic
    Metadata:
      DockerTag: latest
      Dockerfile: Dockerfile
      DockerContext: ./